name: test_1
description: '简单易用的生理期记录工具'
publish_to: 'none'
version: 0.4.18

environment:
  sdk: ^3.7.2

dependencies:
  table_calendar: ^3.0.9
  package_info_plus: ^4.0.0
  flutter:
    sdk: flutter
  provider: ^6.1.1
  sqflite: ^2.3.3
  path: ^1.8.3
  flutter_localizations:
    sdk: flutter
  local_auth: ^2.3.0
  local_auth_android: ^1.0.49
  shared_preferences: ^2.5.3
  path_provider: ^2.1.1
  file_picker: ^10.1.2
  encrypt: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
